In [26]:
import numpy as np
import pandas as pd

In [27]:
x = np.array ([[1,2,3,4,5],
               [6,7,8,0,10],
               [11,12,13,14,15],
               [21,22,23,24,25]])

In [28]:
print(x[:, 2]) # return only the third column of x

[ 3  8 13 23]


In [29]:
print(x[:1,2]) # return the element at row 2, column 3

[3]


In [30]:
print(x[3,:]) #return only row 4 of x

[21 22 23 24 25]


In [35]:
print(x[2,:])  #return the 3rd row of x, but only every other element- also called stride = 2
stride =2


[11 12 13 14 15]
